version: '2'
services:
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
  
  editor:
    build: "."
    image: editor
    working_dir: /srv/www/editor
    expose:
      - "4000"
      - "4001"
    volumes:
      - .:/srv/www/editor
    working_dir: /srv/www/editor

    command: 'bundle exec foreman start'
    ports:
      - "4000:4000"
      - "4001:4001"